### PR TITLE
update markdown indention

### PR DESCRIPTION
**Pull request by 3limin4t0r**
Changed indention from 2 to 4 spaces.

### CODE REVIEW

**Comment by bbatsov** [comment]
I guess you've checked that this solved the problem you reported originally, right?

**Comment by bbatsov** [comment]
This seems to indicate you're right http://brettterpstra.com/2015/08/24/write-better-markdown/#indentation

We'll likely have to do something similar with the other guides as well. //cc @Darhazer @pirj

**Comment by 3limin4t0r** [comment]
> I guess you've checked that this solved the problem you reported originally, right?

@bbatsov Yes, I check if this resolved the issue. I attached the correctly generated PDF to the issue in my last comment (https://github.com/rubocop-hq/ruby-style-guide/issues/727#issuecomment-422367549). This also includes the command to generate the PDF so you can test it for yourself if you'd like.

**Comment by bbatsov** [comment]
Thanks for tackling this! 

If you have some time and desire - you might also fix our Rails and RSpec guides as well. :-)

**Comment by 3limin4t0r** [comment]
@bbatsov I've created PRs for them, see the references above.

**Pull request merged**
