### PR TITLE
Add "Float Comparison" section

### PR DESCRIPTION
**Pull request by fatkodima**

### CODE REVIEW

**Comment by marcandre** [comment]
LGTM. Did you want to mention the only exception I can think of which is `if x == Float::INFINITY`?

**Comment by fatkodima** [comment]
Updated. Also mentioned `Float::NAN`.

**Comment by marcandre** [comment]
Actually you should never compare to `NAN`:
```ruby
Float::NAN == Float::NAN # => false!!
```

**Comment by fatkodima** [comment]
Yes, sure, my bad, you're right, sorry. Removed that.

**Comment by bbatsov** [comment]
We need a lint cop for that! :D

**Pull request merged**
